server:
    port:
        5000
spring:
    datasource:
        url: jdbc:postgresql://ec2-34-233-214-228.compute-1.amazonaws.com:5432/dea995f1tslhov
        username: evbxmxlhdxpeem
        password: 8ae514930c53eb4a47332facadbddb3b36b7bd8e0514aecb8e86d85b9386b643

    jpa:
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update

    profiles:
        active: ${PROFILE}